# typed: true

# DO NOT EDIT MANUALLY
# This is an autogenerated file for types exported from the `postgresql` gem.
# Please instead update this file by running `bin/tapioca gem postgresql`.


# source://postgresql//lib/postgresql/version.rb#1
module Postgresql; end

# source://postgresql//lib/postgresql/version.rb#2
Postgresql::VERSION = T.let(T.unsafe(nil), String)
