# typed: true

# DO NOT EDIT MANUALLY
# This is an autogenerated file for types exported from the `tilt` gem.
# Please instead update this file by running `bin/tapioca gem tilt`.


# Namespace for Tilt. This module is not intended to be included anywhere.
#
# source://tilt//lib/tilt/template.rb#2
module Tilt; end

# @private
#
# source://tilt//lib/tilt/template.rb#4
module Tilt::CompiledTemplates; end

# ERB template implementation. See:
# http://www.ruby-doc.org/stdlib/libdoc/erb/rdoc/classes/ERB.html
#
# source://tilt//lib/tilt/erb.rb#8
class Tilt::ERBTemplate < ::Tilt::Template
  # @return [Boolean]
  #
  # source://tilt//lib/tilt/erb.rb#60
  def freeze_string_literals?; end

  # ERB generates a line to specify the character coding of the generated
  # source in 1.9. Account for this in the line offset.
  #
  # source://tilt//lib/tilt/erb.rb#55
  def precompiled(locals); end

  # source://tilt//lib/tilt/erb.rb#44
  def precompiled_postamble(locals); end

  # source://tilt//lib/tilt/erb.rb#36
  def precompiled_preamble(locals); end

  # source://tilt//lib/tilt/erb.rb#31
  def precompiled_template(locals); end

  # source://tilt//lib/tilt/erb.rb#11
  def prepare; end
end

# source://tilt//lib/tilt/erb.rb#9
Tilt::ERBTemplate::SUPPORTS_KVARGS = T.let(T.unsafe(nil), Array)

# @private
#
# source://tilt//lib/tilt/template.rb#11
Tilt::LOCK = T.let(T.unsafe(nil), Thread::Mutex)

# source://tilt//lib/tilt/template.rb#416
class Tilt::StaticTemplate < ::Tilt::Template
  # Static templates never allow script.
  #
  # @return [Boolean]
  #
  # source://tilt//lib/tilt/template.rb#439
  def allows_script?; end

  # Raise NotImplementedError, since static templates
  # do not support compiled methods.
  #
  # @raise [NotImplementedError]
  #
  # source://tilt//lib/tilt/template.rb#434
  def compiled_method(locals_keys, scope_class = T.unsafe(nil)); end

  # Static templates always return the prepared output.
  #
  # source://tilt//lib/tilt/template.rb#428
  def render(scope = T.unsafe(nil), locals = T.unsafe(nil)); end

  protected

  # source://tilt//lib/tilt/template.rb#445
  def prepare; end

  private

  # Do nothing, since compiled method cache is not used.
  #
  # source://tilt//lib/tilt/template.rb#452
  def set_compiled_method_cache; end

  class << self
    # source://tilt//lib/tilt/template.rb#417
    def subclass(mime_type: T.unsafe(nil), &block); end
  end
end

# @private
#
# source://tilt//lib/tilt/template.rb#8
Tilt::TOPOBJECT = Tilt::CompiledTemplates

# Base class for template implementations. Subclasses must implement
# the #prepare method and one of the #evaluate or #precompiled_template
# methods.
#
# source://tilt//lib/tilt/template.rb#16
class Tilt::Template
  # Create a new template with the file, line, and options specified. By
  # default, template data is read from the file. When a block is given,
  # it should read template data and return as a String. When file is nil,
  # a block is required.
  #
  # All arguments are optional.
  #
  # @raise [ArgumentError]
  # @return [Template] a new instance of Template
  #
  # source://tilt//lib/tilt/template.rb#61
  def initialize(file = T.unsafe(nil), line = T.unsafe(nil), options = T.unsafe(nil)); end

  # The basename of the template file.
  #
  # source://tilt//lib/tilt/template.rb#106
  def basename(suffix = T.unsafe(nil)); end

  # The compiled method for the locals keys and scope_class provided.
  # Returns an UnboundMethod, which can be used to define methods
  # directly on the scope class, which are much faster to call than
  # Tilt's normal rendering.
  #
  # source://tilt//lib/tilt/template.rb#147
  def compiled_method(locals_keys, scope_class = T.unsafe(nil)); end

  # A path ending in .rb that the template code will be written to, then
  # required, instead of being evaled.  This is useful for determining
  # coverage of compiled template code, or to use static analysis tools
  # on the compiled template code.
  #
  # source://tilt//lib/tilt/template.rb#35
  def compiled_path; end

  # Set the prefix to use for compiled paths.
  #
  # source://tilt//lib/tilt/template.rb#133
  def compiled_path=(path); end

  # Template source; loaded from a file or given directly.
  #
  # source://tilt//lib/tilt/template.rb#18
  def data; end

  # The filename used in backtraces to describe the template.
  #
  # source://tilt//lib/tilt/template.rb#118
  def eval_file; end

  # The name of the file where the template data was loaded from.
  #
  # source://tilt//lib/tilt/template.rb#21
  def file; end

  # The line number in #file where template data was loaded from.
  #
  # source://tilt//lib/tilt/template.rb#24
  def line; end

  # An empty Hash that the template engine can populate with various
  # metadata.
  #
  # source://tilt//lib/tilt/template.rb#124
  def metadata; end

  # The template file's basename with all extensions chomped off.
  #
  # source://tilt//lib/tilt/template.rb#111
  def name; end

  # A Hash of template engine specific options. This is passed directly
  # to the underlying engine and is not used by the generic template
  # interface.
  #
  # source://tilt//lib/tilt/template.rb#29
  def options; end

  # Render the template in the given scope with the locals specified. If a
  # block is given, it is typically available within the template via
  # +yield+.
  #
  # source://tilt//lib/tilt/template.rb#101
  def render(scope = T.unsafe(nil), locals = T.unsafe(nil), &block); end

  protected

  # The encoding of the source data. Defaults to the
  # default_encoding-option if present. You may override this method
  # in your template class if you have a better hint of the data's
  # encoding.
  #
  # source://tilt//lib/tilt/template.rb#169
  def default_encoding; end

  # Execute the compiled template and return the result string. Template
  # evaluation is guaranteed to be performed in the scope object with the
  # locals specified and with support for yielding to the block.
  #
  # This method is only used by source generating templates. Subclasses that
  # override render() may not support all features.
  #
  # source://tilt//lib/tilt/template.rb#192
  def evaluate(scope, locals, &block); end

  # Generates all template source by combining the preamble, template, and
  # postamble and returns a two-tuple of the form: [source, offset], where
  # source is the string containing (Ruby) source code for the template and
  # offset is the integer line offset where line reporting should begin.
  #
  # Template subclasses may override this method when they need complete
  # control over source generation or want to adjust the default line
  # offset. In most cases, overriding the #precompiled_template method is
  # easier and more appropriate.
  #
  # source://tilt//lib/tilt/template.rb#224
  def precompiled(local_keys); end

  # source://tilt//lib/tilt/template.rb#262
  def precompiled_postamble(local_keys); end

  # source://tilt//lib/tilt/template.rb#258
  def precompiled_preamble(local_keys); end

  # A string containing the (Ruby) source code for the template. The
  # default Template#evaluate implementation requires either this
  # method or the #precompiled method be overridden. When defined,
  # the base Template guarantees correct file/line handling, locals
  # support, custom scopes, proper encoding, and support for template
  # compilation.
  #
  # @raise [NotImplementedError]
  #
  # source://tilt//lib/tilt/template.rb#254
  def precompiled_template(local_keys); end

  # Do whatever preparation is necessary to setup the underlying template
  # engine. Called immediately after template data is loaded. Instance
  # variables set in this method are available when #evaluate is called.
  #
  # Empty by default as some subclasses do not need separate preparation.
  #
  # source://tilt//lib/tilt/template.rb#180
  def prepare; end

  # @return [Boolean]
  #
  # source://tilt//lib/tilt/template.rb#171
  def skip_compiled_encoding_detection?; end

  private

  # source://tilt//lib/tilt/template.rb#407
  def binary(string); end

  # source://tilt//lib/tilt/template.rb#341
  def bind_compiled_method(method_source, offset, scope_class); end

  # source://tilt//lib/tilt/template.rb#318
  def compile_template_method(local_keys, scope_class = T.unsafe(nil)); end

  # source://tilt//lib/tilt/template.rb#370
  def eval_compiled_method(method_source, offset, scope_class); end

  # source://tilt//lib/tilt/template.rb#388
  def extract_encoding(script, &block); end

  # source://tilt//lib/tilt/template.rb#392
  def extract_magic_comment(script); end

  # @return [Boolean]
  #
  # source://tilt//lib/tilt/template.rb#403
  def freeze_string_literals?; end

  # source://tilt//lib/tilt/template.rb#374
  def load_compiled_method(path, method_source); end

  # source://tilt//lib/tilt/template.rb#297
  def local_extraction(local_keys); end

  # source://tilt//lib/tilt/template.rb#270
  def process_arg(arg); end

  # source://tilt//lib/tilt/template.rb#284
  def read_template_file; end

  # source://tilt//lib/tilt/template.rb#293
  def set_compiled_method_cache; end

  # source://tilt//lib/tilt/template.rb#382
  def unbind_compiled_method(method_name); end

  class << self
    # Use `.metadata[:mime_type]` instead.
    #
    # source://tilt//lib/tilt/template.rb#45
    def default_mime_type; end

    # Use `.metadata[:mime_type] = val` instead.
    #
    # source://tilt//lib/tilt/template.rb#50
    def default_mime_type=(value); end

    # An empty Hash that the template engine can populate with various
    # metadata.
    #
    # source://tilt//lib/tilt/template.rb#40
    def metadata; end
  end
end

# source://tilt//lib/tilt/template.rb#183
Tilt::Template::CLASS_METHOD = T.let(T.unsafe(nil), UnboundMethod)

# source://tilt//lib/tilt/template.rb#184
Tilt::Template::USE_BIND_CALL = T.let(T.unsafe(nil), TrueClass)
