default: &default
  adapter: postgresql
  encoding: unicode
  host: localhost
  pool: <%= ENV.fetch("RAILS_MAX_THREADS") { 5 } %>
  username: <%= ENV["DATABASE_USERNAME"] %>
  password: <%= ENV["DATABASE_PASSWORD"] %>

development:
  <<: *default
  database: betmate_development

test:
  <<: *default
  database: betmate_testing

staging:
  <<: *default
  database: betmate_staging

production:
  <<: *default
  database: betmate_production

