# DO NOT EDIT MANUALLY
# This is an autogenerated file for unresolved constants.
# Please instead update this file by running `bin/tapioca todo`.

# typed: false

module FetchFixturesWorker::Sidekiq::Worker; end
module PlayerStatistic::PlayerFoulsStatistic; end
module PlayerStatistic::PlayerSubstitutesStatistic; end
module PlayerSubstituesStatistic::PlayerSubstitutesStatistic; end
